#version: "3.8"
services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "{{ bitwarden_data_dir }}:/data"
    ports:
      - "{{ bitwarden_port }}:80"
