---

- name: install nginx
  apt:
    name:
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true
  register: nginxinstall

- name: debug
  debug:
    msg: "The {{ nginxinstall.rc }}"

- name : start nginx
  service:
    name: nginx
    state: started
  become: true

...  