- name: install nginx
  apt:
    name:
      - nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name : start nginx
  service:
    name: nginx
    state: start
  become: yes

