# - name: Deploy Bitwarden
#   community.docker.docker_compose_v2:
#     # project_src: "{{ bitwarden_data_dir }}"
#     project_src: files/docker-compose.yaml
#   notify: Restart Bitwarden
#   tags: run

- name: Deploy Bitwarden
  shell: docker-compose  -f /home/ec2-user/docker-compose.yaml up
  notify: Restart Bitwarden
  tags: run

# - name: Wait for Bitwarden
#   uri:
#     url: "http://localhost:{{ bitwarden_port }}"
#     status_code: 200
#   register: bw
#   retries: 10
#   delay: 5
#   until: bw.status == 200
