- name: Install Docker
  dnf:
    name:
      - docker
      - docker-compose-plugin
    state: present
  tags: install

- name: Enable & start Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ bitwarden_user }}"
    groups: docker
    append: true
