# - name: Install Docker
#   dnf:
#     name:
#       - docker
#       - docker-compose-plugin
#     state: present
#   tags: install

- name: Install Docker compose
  shell: sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
  tags: install


- name: Enable & start Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ bitwarden_user }}"
    groups: docker
    append: true

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/docker-compose.yaml
    dest: /home/ec2-user/docker-compose.yaml
    owner: ec2-user
    group: ec2-user
    mode: '0755'