- name: Installer les dépendances système
  apt:
    name:
      - wget
      - tar
      - curl
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: true

- name: Télécharger Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extraire Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Copier les binaires Prometheus
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_dir }}/{{ item }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
    remote_src: true
  loop:
    - prometheus
    - promtool