---
- name: Installation des pre-requis Prometheus
  import_tasks: prerequisites.yml

- name: Télécharger Prometheus
  import_tasks: install.yml 

- name: Configurer et démarrer le service Prometheus
  import_tasks: config.yml
