---
- name: Build image and with build args
  docker_image:
    name: myimagebel
    build:
      path: /var/jenkins_home/workspace/ansible/tools/Dockerfile
      args:
        log_volume: /var/log/myapp
        listen_port: 8080
    source: build

- name: Deploiement du conteneur
  docker_container:
    name: web1
    state: started
    image: ubuntu:14.04
    ports: 9000:80
    command: sleep infinity



...