---
# defaults file for vault

# defaults/main.yml
vault_version: "1.15.5"
vault_download_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
vault_install_path: "/usr/local/bin"
vault_data_path: "/etc/vault.d/data"
vault_config_path: "/etc/vault.d/vault.hcl"
vault_listener_address: "192.168.1.150:8200"

