---

- name: install postgres
  apt:
    name:
      - postgresql
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Exec SQL scripts
  community.postgresql.postgresql_query:
    login_user: postgres
    login_db: postgres
    query: SELECT * FROM version();
  become: yes
  become_user: postgres
