[frontend]
gcp ansible_host=34.59.91.97 ansible_user=lidobel ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3.9

[middle]
gcp ansible_host=34.59.91.97 ansible_user=lidobel ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3.9

[docker]
gcp

[vault_servers]
gcp

[observability]
gcp ansible_host=34.59.91.97 ansible_user=lidobel ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3.9

[bdd]
bdd1 ansible_host=192.168.1.105 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3.6

[all:children]
frontend
middle
bdd