# handlers/main.yml
---
- name: redémarrer vault
  become: true
  service:
    name: vault
    state: restarted

- name: Stop Vault
  become: true
  shell: pkill "vault"
  ignore_errors: true

- name: Start Vault
  become: true
  shell: pkill "vault"
  ignore_errors: true

- name: Status Vault
  ansible.builtin.uri:
    url: "{{ vault_addr }}/v1/sys/health"
    method: GET
    status_code: [200, 429, 472, 473, 501, 503]
    return_content: yes
    ca_path: "/etc/ssl/certs/ca_chain.crt"
  register: vault_health
  failed_when: false