---

- name: Check Vault health status
  ansible.builtin.uri:
    url: "https://192.168.1.150:{{ hcp_server_port }}/v1/sys/health"
    method: GET
    validate_certs: false
  register: vault_status
  failed_when: false
