---

- name: Check du statut de Vault
  shell: vault status
  args:
    executable: /bin/bash
  register: vault_status
  ignore_errors: true

- name: Installation des pre-requis
  import_tasks: prerequis.yml
  when: vault_status.rc != 0

- name: Déploiement et configuration de Vault
  import_tasks: deploy.yml
  when: vault_status.rc != 0  

- name: Test de l'installation de Vault
  import_tasks: test.yml

# tasks file for vault
# tasks/main.yml


#- name: Créer service systemd Vault
#  become: true
#  copy:
#    dest: /etc/systemd/system/vault.service
#    content: |
#      [Unit]
#      Description=HashiCorp Vault
#      After=network.target

#      [Service]
#      ExecStart=/usr/bin/vault server -config={{ vault_config_path }}
#      Restart=on-failure
#      LimitNOFILE=65536

#      [Install]
#      WantedBy=multi-user.target
#  notify: reload systemd



#- name: Démarrer Vault
#  become: true
#  command: "nohup vault server -config={{ vault_config_path }} > /var/log/vault.log 2>&1 &"
#  async: 10
#  poll: 0
  #creates: /var/run/vault.pid  # Créez ce fichier dans vault server

#- name: Démarrer et activer Vault
#  become: true
#  systemd:
#    name: vault
#    state: started
#    enabled: true
#    daemon_reload: true

#- name: Attendre que Vault démarre
#  become: true
#  wait_for:
#    host: "{{ vault_listener_address }}"
#    port: 8200
#    delay: 10
#    timeout: 60
#    state: started

# - name: Initialiser Vault
#   become: true
#   command: "vault operator init"
#   environment:
#     VAULT_ADDR: "http://192.168.1.150:8200"
#   register: vault_init_output
#   when: ansible_facts['distribution'] == "Ubuntu"
#   #ignore_errors: true

# - name: Déverrouiller Vault (unseal)
#   become: true
#   command: "vault operator unseal {{ item }}"
#   loop: "{{ vault_init_output.stdout_lines[0:3] }}"

# - name: Se connecter à Vault avec le token root
#   become: true
#   command: "vault login {{ vault_init_output.stdout_lines[3] }}"

