---
# tasks file for vault
# tasks/main.yml
- name: Installer les pré-requis
  become: true
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Télécharger Vault
  become: true
  get_url:
    url: "{{ vault_download_url }}"
    dest: "/tmp/vault.zip"
  when: primo_install is defined 

- name: Décompresser Vault
  become: true
  unarchive:
    src: "/tmp/vault.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Déplacer Vault dans /usr/local/bin
  become: true
  command: mv /tmp/vault {{ vault_install_path }}/vault creates={{ vault_install_path }}/vault

- name: Créer un utilisateur Vault
  become: true
  user:
    name: vault
    system: yes
    home: "/etc/vault.d"
    shell: "/bin/false"

- name: Créer le dossier de configuration
  become: true
  file:
    path: "/etc/vault.d"
    state: directory
    owner: vault
    group: vault
    mode: "0755"

- name: Copier le fichier de configuration vault.hcl
  become: true
  copy:
    src: "vault.hcl"
    dest: "{{ vault_config_path }}"
    owner: vault
    group: vault
    mode: "0644"

- name: Créer le dossier pour stocker les données de Vault
  become: true
  file:
    path: "{{ vault_data_path }}"
    state: directory
    owner: vault
    group: vault
    mode: "0755"

#- name: Créer service systemd Vault
#  become: true
#  copy:
#    dest: /etc/systemd/system/vault.service
#    content: |
#      [Unit]
#      Description=HashiCorp Vault
#      After=network.target

#      [Service]
#      ExecStart=/usr/bin/vault server -config={{ vault_config_path }}
#      Restart=on-failure
#      LimitNOFILE=65536

#      [Install]
#      WantedBy=multi-user.target
#  notify: reload systemd

- name: Arrêter Vault existant
  become: true
  shell: pkill -f "vault server" || true
  ignore_errors: true

- name: Démarrer Vault
  shell: "vault server -config={{ vault_config_path }}"
  register: vault_init_output
  async: 45
  poll: 10
  #executable: /bin/bash

- name: Attendre Vault
  wait_for:
    host: "192.168.1.150"  # ← Ajoutez cette ligne
    port: 8200
    delay: 10
    timeout: 60

#- name: Démarrer Vault
#  become: true
#  command: "nohup vault server -config={{ vault_config_path }} > /var/log/vault.log 2>&1 &"
#  async: 10
#  poll: 0
  #creates: /var/run/vault.pid  # Créez ce fichier dans vault server

#- name: Démarrer et activer Vault
#  become: true
#  systemd:
#    name: vault
#    state: started
#    enabled: true
#    daemon_reload: true

#- name: Attendre que Vault démarre
#  become: true
#  wait_for:
#    host: "{{ vault_listener_address }}"
#    port: 8200
#    delay: 10
#    timeout: 60
#    state: started

#- name: Initialiser Vault
#  become: true
#  command: "vault operator init"
#  environment:
#    VAULT_ADDR: "http://192.168.1.150:8200"
#  register: vault_init_output
#  when: ansible_facts['distribution'] == "Ubuntu"
  #ignore_errors: true

- name: Déverrouiller Vault (unseal)
  become: true
  command: "vault operator unseal {{ item }}"
  loop: "{{ vault_init_output.stdout_lines[0:3] }}"

- name: Se connecter à Vault avec le token root
  become: true
  command: "vault login {{ vault_init_output.stdout_lines[3] }}"

