- name: Installer les pré-requis
  become: true
  apt:
    name:
      - curl
      - unzip
    state: present

- name: Télécharger Vault
  become: true
  get_url:
    url: "{{ vault_download_url }}"
    dest: "/tmp/vault.zip"
  when: primo_install is defined 

- name: Décompresser Vault
  become: true
  unarchive:
    src: "/tmp/vault.zip"
    dest: "/tmp/"
    remote_src: yes

- name: Déplacer Vault dans /usr/local/bin
  become: true
  command: mv /tmp/vault {{ vault_install_path }}/vault creates={{ vault_install_path }}/vault

- name: Créer un utilisateur Vault
  become: true
  user:
    name: vault
    system: yes
    home: "/etc/vault.d"
    shell: "/bin/false"

- name: Créer le dossier de configuration
  become: true
  file:
    path: "/etc/vault.d"
    state: directory
    owner: vault
    group: vault
    mode: "0755"

# - name: Copier le fichier de configuration vault.hcl
#   become: true
#   copy:
#     src: "vault.hcl"
#     dest: "{{ vault_config_path }}"
#     owner: vault
#     group: vault
#     mode: "0644"

- name: Depot du template de configuration hcl
  become: true
  template:
    src: "vault.hcl.j2"
    dest: "{{ vault_config_path }}"
    owner: vault
    group: vault
    mode: "0644"

- name: Créer le dossier pour stocker les données de Vault
  become: true
  file:
    path: "{{ vault_data_path }}"
    state: directory
    owner: vault
    group: vault
    mode: "0755"