---
- name: Récupérer un secret depuis Vault
  debug:
    msg: |
      Username: {{ lookup('community.hashi_vault.hashi_vault', 
                  'secret=secret/data/dev/database:username 
                  url={{ vault_addr }} 
                  auth_method=token 
                  token={{ vault_root_token }}') }}