# - name: Lire le secret depuis Vault
#   shell: 'vault kv get -token="{{ vault_root_token }}" -address="{{ vault_addr }}" -mount="ansible" "database/postgres"'
#   args:
#     executable: /bin/bash

- name: Check du statut de Vault
  shell: vault status
  args:
    executable: /bin/bash

- name: Récupérer le secret via la CLI Vault
  ansible.builtin.shell: |
    export VAULT_ADDR="{{ vault_addr }}"
    export VAULT_TOKEN="{{ vault_root_token }}"
    vault kv get -mount="ansible" -format=json "database/postgres"
  register: vault_output

- name: Parser le résultat
  set_fact:
    postgres_vars: "{{ vault_output.stdout | from_json }}"