bitwarden_version: "latest"

#bitwarden_domain: "https://vault.example.com"
bitwarden_domain: "http://51.44.110.118:8000"
bitwarden_port: 8000

bitwarden_data_dir: /opt/bitwarden
bitwarden_user: bitwarden

bitwarden_admin_token: "4fe17c064c45ff11d39b51b1a46f5177c7528c14f4a4362a0a766b194ce91159"
bitwarden_smtp_enabled: false
