bitwarden_version: "latest"

bitwarden_domain: "https://vault.example.com"
bitwarden_port: 8000

bitwarden_data_dir: /opt/bitwarden
bitwarden_user: bitwarden

bitwarden_admin_token: ""
bitwarden_smtp_enabled: false
