- hosts: frontend
  roles:
    - frontend

# - hosts: middle
#   roles:
#     - middle
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Installer la collection community.docker
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker
        
- hosts: docker
  roles:
    - docker
  become: true

- hosts: docker
  roles:
    - bitwarden
  become: true
  tags: bitwarden
  when: install_bitwarden

- hosts: bdd
  roles:
    - bdd
  become: true