# Installation de Collections utilisée dans ce playbook 
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Installer les collections avec des versions spécifiques
      ansible.builtin.command:
        # On utilise item.name et item.version
        cmd: "ansible-galaxy collection install {{ item.name }}:{{ item.version }} --force"
      loop:
        - { name: 'community.hashi_vault', version: '7.1.0' }
        - { name: 'community.docker', version: '3.4.7' } # On garde ta version stable actuelle
      vars:
      # On définit le chemin ici pour que les modules suivants le trouvent
        ansible_collections_paths: 
          - /var/jenkins_home/.ansible/collections/ansible_collections
    
- name: Installation de Python sans dépendances
  hosts: gcp
  gather_facts: false  # TRÈS IMPORTANT : empêche Ansible de chercher Python au début
  become: true         # Nécessaire pour installer des paquets

  tasks:
    - name: Installer python3.8 s'il est absent (via SSH raw)
      raw: test -e /usr/bin/python3 || (apt -y update && apt -y install python3-minimal)
      changed_when: false

    - name: Forcer la détection des faits (maintenant que Python est là)
      setup:
  
# playbook_cockpit.yml
- name: Installer Cockpit sur les serveurs
  hosts: gcp
  become: true
  vars:
    cockpit_idle_timeout: "3600"  # 1 heure
    cockpit_password_auth: "true"
  roles:
    - supervision
  post_tasks:
    - name: Afficher l'URL d'accès
      debug:
        msg: "Cockpit est accessible sur https://{{ ansible_default_ipv4.address }}:9090"

# - hosts: frontend
#   roles:
#     - frontend

- hosts: frontend
  tasks:
    - import_role:
        name: frontend
      when: install_frontend
  become: true
  tags: frontend
  
- hosts: docker
  roles:
    - docker
  become: true

- hosts: docker
  become: true
  tags: bitwarden
  tasks:
    - import_role:
        name: bitwarden
      when: install_bitwarden

- name: Installer et configurer HashiCorp Vault
  hosts: vault_servers
  environment: 
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_token }}"
  become: true
  roles:
    - hashicorpvault
  tags: vault

- hosts: bdd
  roles:
    - bdd
  become: true